<footer>
    <nav>
        <ul>
            <li class="footmenu"><a href="index.php" title="This takes you to the Home page.">Home</a></li>
            <li class="footmenu"><a href="jobs.php" title="This takes you to the Position Descriptions page.">Jobs</a></li>
            <li class="footmenu"><a href="apply.php" title="This takes you to the Job Applications page.">Apply</a></li>
            <li class="footmenu"><a href="about.php" title="This takes you to the About Us page.">About</a></li>
            <li class="footmenu"><a href="mailto:info@rainyseason.com.au" title="Allows you to contact our email.">Email</a></li>
        </ul>

        <p>&#169; Swinburne University of Technology  &sol;  <a href="https://rainy-season.atlassian.net/">Rainy Season Jira</a>  &sol;  <a href="https://github.com/Bigteaforfolks/sw_cos10026_rainy_season" target="_blank">Github Repository</a></p>
    </nav>
</footer>