<footer>
    <nav>
        <div class="footmenu">
            <?php 
                include("nav.inc"); 
            ?>
        </div>

        <p>&#169; Swinburne University of Technology  &sol;  <a href="https://rainy-season.atlassian.net/">Rainy Season Jira</a>  &sol;  <a href="https://github.com/Bigteaforfolks/sw_cos10026_rainy_season_part2" target="_blank">Github Repository</a></p>
    </nav>
</footer>