<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Home page of the Rainy Season website.">
    <meta name="keywords" content="Rainy Season, Home, Company, Profile, About, Index">
    <meta name="author" content="Jacob Ang">
    <title>Home &sol; Rainy Season</title>

    <!-- Reference to external CSS file -->
    <link href="styles/styles.css" rel="stylesheet">
</head>

<body id="home-page">
    <?php
        include 'header.inc';
    ?>

    <section id="landing">
        <img id="landing_logo" src="images/logo.png" alt="Rainy Season Logo">
        <h2>Weathering the Storm</h2>

        <!-- Line 41 was generated by ChatGPT -->
        <!-- Prompt: "Write a brief company mission statement for a tech company that works in the vehicle history verification/checking field" -->
        <p>Our mission is to revolutionize the used car buying experience by providing transparent, secure, and reliable vehicle history verification. Through cutting-edge technology and data analytics, we empower consumers and dealers with trusted insights, ensuring peace of mind and informed decisions for every vehicle transaction.</p>
        <p>We operate the "Stormcloud" database, which users can search and and filter through to find the history of used cars from all over the world.</p>
    </section>

    <hr class="separator">

    <!-- A visualisation including descriptions of the different pages of the site -->
    <section id="pages">
        <div class="jobs-item">
            <a href="jobs.php">
                <img id="jobs-img" src="images/jobs.jpg" alt="Jpbs tile background">
                <div class="pages-text">
                    <h2>Jobs</h2>
                    <p>Discover all the available positions at Rainy Season to find the right fit for you and your unique skillset&excl;</p>
                </div>
            </a>
        </div>
        <div class="apply-item">
            <a href="apply.php">
                <img id="apply-img" src="images/apply.jpg" alt="Apply tile background">
                <div class="pages-text">
                    <h2>Apply</h2>
                    <p>Submit your details to Rainy Season to apply for a position&excl;</p>
                </div>
            </a>
        </div>
        <div class="about-item">
            <a href="about.php">
                <img id="about-img" src="images/team_photo.png" alt="About tile background">
                <div class="pages-text">
                    <h2>About</h2>
                    <p>Learn about the minds behind the company</p>
                </div>
            </a>
        </div>
    </section>

    <hr class="separator">

    <section class="description description--hiring">

        <h2>Rainy Season is hiring&excl;</h2>

        <!--
        Used DeepSeek AI to generate the description. Prompt:
            Scenario:
            An IT company wants to develop a website that will enable it to advertise vacant positions. These have a ‘position description’ that sets out the qualifications, skills and knowledge required. Potential applicants for the position will be able to submit an online form to apply for a position.

            Company name: Rainy Season

            Create a small paragraph used on the main page.      
        -->

        <p>At Rainy Season, we believe in nurturing talent and innovation. Explore our latest job openings and find the perfect opportunity to grow with us. Each position comes with a detailed description outlining the qualifications, skills, and knowledge required. Ready to join our dynamic team&#63; Submit your application online today and take the next step in your career journey&excl;</p>
    </section>

    <?php
        include 'footer.inc';
    ?>
</body>
</html>