<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Jobs page of Rainy Season website">
    <meta name="keywords" content="Rainy Season, Jobs, Apply, Openings, Available, Work">
    <meta name="author" content="Oakley Tang">
    <title>Jobs &sol; Rainy Season</title>

    <!-- Reference to external CSS file -->
    <link href="styles/styles.css" rel="stylesheet">
</head>

<body id="jobs-page">
    <?php
        include 'header.inc';
    ?>

    <!-- Jobs page description -->
    <section class="description">
        <h2>Job openings at Rainy Season</h2>
        <p>Discover all the available positions at Rainy Season to find the right fit for you and your unique skillset!</p>
    </section>

    <?php

    session_start();
    require_once("settings.php");

    $conn = mysqli_connect($host, $user, $pwd, $sql_db);

    if ($conn) {
        $query = "SELECT * FROM eoi";
        $result = mysqli_query ($conn, $query);
        if ($result && mysqli_num_rows($result) > 0) {
            $jobs = mysqli_fetch_all($result, MYSQLI_ASSOC);

            ?>
            <!-- Aside for company and general job information -->
            <div class="aside">
                <aside>
                    <h3>Currently available positions</h3>
                    <ul>
                        <?php
                            foreach ($jobs as $row) {
                                echo "<li>" . htmlspecialchars($row['position']) . "</li>";
                            }
                        ?>
                    </ul>
                
                    <h3>Perks offered to all positions</h3>
                    <ul>
                        <li>14 days paid leave (after 6 months)</li>
                        <li>New Year and winter breaks</li>
                        <li>Free snacks and drinks</li>
                        <li>Casual dress code</li>
                        <li>Condolence leave</li>
                        <li>Parental leave</li>
                        <li>Commute allowance</li>
                    </ul>

                    <h3 id="apply-link"><a href="apply.php" title="Application page">Click here to apply!</a></h3>
                    
                </aside>
            </div>

            <section id="about">
                <h3>About Rainy Season</h3>
            
                    <!-- Line 71 was generated by ChatGPT -->
                    <!-- Prompt: "Write a brief company mission statement for a tech company that works in the vehicle history verification/checking field" -->
                    <p>Our mission is to revolutionize the used car buying experience by providing transparent, secure, and reliable vehicle history verification. Through cutting-edge technology and data analytics, we empower consumers and dealers with trusted insights, ensuring peace of mind and informed decisions for every vehicle transaction.</p>
                    <p>We operate the "Stormcloud" database, which users can search and and filter through to find the history of used cars from all over the world.</p>
            </section>

            <hr class="separator">

            <div class="positions">
        
                <!-- This section contains AI generated content which was generated using manually written content as input -->
                <?php
                foreach ($jobs as $row) {
                ?>
                
                <section>
                    <h2><?php echo htmlspecialchars($row['position']); ?></h2>
                    <h3>Reference number: <?php echo htmlspecialchars($row['job_reference_number']); ?></h3>
                    <h3>Salary range: $<?php echo number_format($row['salary_min']); ?> to $<?php echo number_format($row['salary_max']); ?></h3>
                    
                    <div class="job-basic-info">
                        
                        <!-- # This description was manually written first, then ChatGPT was used to extend it -->
                        <!-- Prompt: [pasted all text content contained in the section "cybersecurity-specialist", with the description below replaced with the draft description that can be found in drafts/jobs.txt] + "Extend the job description paragraph to ensure the whole description reaches 200+ words"-->
                        <p><?php echo htmlspecialchars($row['description']); ?></p> 
                        <!-- end of AI generated content-->
                        
                        <p>This position reports to the <span class="superior"><?php echo htmlspecialchars($row['reports_to']); ?></span>.</p>
                    </div>

                    <div class="responsibilities">
                        <h3>Key responsibilities, in order of priority</h3>
                        <ol>
                            <li><?php echo htmlspecialchars($row['key_responsibility_1']); ?></li>
                            <li><?php echo htmlspecialchars($row['key_responsibility_2']); ?></li>
                            <li><?php echo htmlspecialchars($row['key_responsibility_3']); ?>s</li>
                        </ol>
                    </div>

                    <div class="preferable-skills">
                        <h3>Essential skills and traits</h3>
                        <ul>    
                            <li><?php echo htmlspecialchars($row['essential_skills_1']); ?></li>
                            <li><?php echo htmlspecialchars($row['essential_skills_2']); ?></li>
                            <li><?php echo htmlspecialchars($row['essential_skills_3']); ?></li>
                        </ul>
                    </div>

                    <div class="preferable-skills">
                        <h3>Preferable skills and traits</h3>
                        <ul>    
                            <li><?php echo htmlspecialchars($row['preferable_skills_1']); ?></li>
                            <li><?php echo htmlspecialchars($row['preferable_skills_2']); ?></li>
                            <li><?php echo htmlspecialchars($row['preferable_skills_3']); ?></li>
                        </ul>
                    </div>

                    <h3 class="back-to-top"><a href="#">Back to top</a></h3>
                </section>

                <hr class="separator">

                    <!-- end of AI generated content-->

        <?php
            }} else { echo "<h2 class='no-positions'>There are no positions open at this time.</h2>";}

            } else { echo "<h2>Unable to connect to the database.</h2>";}
        ?>
    </div>

    <?php
        include 'footer.inc';
    ?>
</body>
</html>