<ul>
    <li class="menu"><a href="index.php" title="This takes you to the Home page.">Home</a></li>
    <li class="menu"><a href="jobs.php" title="This takes you to the Position Descriptions page.">Jobs</a></li>
    <li class="menu"><a href="apply.php" title="This takes you to the Job Applications page.">Apply</a></li>
    <li class="menu"><a href="about.php" title="This takes you to the About Us page.">About</a></li>
    <li class="menu"><a href="mailto:info@rainyseason.com.au" title="Allows you to contact our email.">Email</a></li>
</ul>