<nav>
    <ul>
        <li class="menu"><a href="index.html" title="This takes you to the Home page.">Home</a></li>
        <li class="menu"><a href="jobs.html" title="This takes you to the Position Descriptions page.">Jobs</a></li>
        <li class="menu"><a href="apply.html" title="This takes you to the Job Applications page.">Apply</a></li>
        <li class="menu"><a href="about.html" title="This takes you to the About Us page.">About</a></li>
        <li class="menu"><a href="mailto:info@rainyseason.com.au" title="Allows you to contact our email.">Email</a></li>
    </ul>
</nav>